title:            Hyæna
tagline:          Jekyll Theme
description:      Ole, wie er die Welt sieht
#Comment out url when working locally to resolve base urls correctly
url:              http://hyaena.de

tags_path:        /tags.html
# Owner/author information
owner:
  name:           Olaf Rosendahl
  avatar:         ole-rosendahl.jpg
  bio:            "Du kannst mich Ole nennen."
  email:          ole.rosendahl@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:
  github:         "Hyaena"
  linkedin:       "hyaena"
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/110935071248348737596"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-3270232-1
google_verify: NqZvUMGCiK0Y1iYR6d-wt-wpmWgmjn6rDSzFx4T0ZY4
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Internal pages/posts to include in top navigation
links:
  - title: Ole
    atitle: "Was es so über mich zu sagen gibt…"
    url: /about
  - title: Artikel
    atitle: "Übersicht aller Artikel."
    url: /articles
  - title: Tags
    atitle: "Übersicht aller Tags"
    url: /tags
  - title: Impressum
    atitle: "All das Zeug, das Du nicht liest…"
    url: /imprint

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
